import { WindowsHeader } from "@/components/WindowsHeader";
import { useWindowSize } from "@/hooks/useWindowSize";
import Head from "next/head";

export default function Home() {
  const { width } = useWindowSize();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {width && width > 1199 ? <WindowsHeader /> : null}
    </>
  );
}
